name: Mirroring

on:
  push:
    branches:
      - master
  delete:
    branches:
      - master

jobs:
  mirroring:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:hodgef/swipe-keyboard.git
          ssh_private_key: ${{ secrets.GL_KEY }}
